
import { BackendFile, Language } from './types';

export const TRANSLATIONS = {
  en: {
    superadmin: "Super Admin (Root)",
    it: "IT Specialist",
    hr: "HR Manager",
    employee: "Employee",
    loginTitle: "Internal Document Management",
    loginDesc: "Select your role to access the system",
    loginBtn: "Login System",
    welcomeAdmin: "Human Resources & Document Management", 
    hrDesc: "Document & Knowledge Management.",
    userDesc: "Search knowledge base & AI Assistant.",
    tabDocs: "Document Repository",
    tabUsers: "User Management",
    tabSystem: "System Console",
    tabDocsDesc: "Upload, organize folders, and manage files",
    tabUsersDesc: "Create users, assign roles, and security",
    settings: "System Settings",
    maintenance: "Maintenance Mode",
    stats: "System Statistics",
    uploadTitle: "Ingest New Data",
    uploadDesc: "Support PDF, Word, Excel, Images, TXT",
    duplicateWarning: "File exists! Replace it?",
    noPermission: "You don't have permission for this action.",
    saveConfig: "Save Configuration",
    download: "Download",
    view: "View",
    back: "Logout",
    searchDocs: "Search documents...",
    filterAll: "All Types",
    files: "Files",
    edit: "Edit",
    editDocTitle: "Edit Document",
    docContent: "Content",
    cancel: "Cancel",
    save: "Save",
    clear: "Clear Chat",
    systemHealth: "System Health",
    vectorDb: "Vector Database",
    storageUsage: "Hybrid Cloud Storage",
    aiModelLabel: "AI Model",
    records: "Records",
    quota: "Combined Quota (Multi-Cloud)",
    configTitle: "System Configuration",
    inferenceEngine: "AI Inference Engine",
    optimized: "Hybrid Storage Enabled",
    maintenanceMode: "Maintenance Mode",
    maintenanceDesc: "Disables user access for updates",
    publicUpload: "Public Upload Access",
    publicUploadDesc: "Allow guests to upload files",
    maxFileSize: "Max Ingest File Size (MB)",
    dbManagement: "Database Management",
    backupData: "Backup System Data",
    integrityCheck: "Data Integrity Check",
    lastBackup: "Last Backup",
    tokenReport: "AI Analytics Dashboard",
    tokensUsed: "Tokens Used",
    requests: "Requests",
    modelStatus: "Model Status",
    logs: "System Logs",
    cloudCapacity: "Internal Cloud Capacity",
    dragDrop: "Drag & Drop Multiple Files",
    dbEmpty: "Database is empty or no match.",
    aiAssistant: "AI Assistant",
    entries: "entries",
    pdfDoc: "PDF Document",
    wordDoc: "Word Document",
    excelSheet: "Excel Sheet",
    textFile: "Text File",
    imageFile: "Image / Scan",
    rootAccess: "Root access granted. System maintenance mode management.",
    createUser: "Create New User",
    userList: "User List",
    username: "Username",
    password: "Password",
    role: "Role",
    create: "Create",
    newChat: "New Chat",
    chatHistory: "History",
    noHistory: "No recent chats",
    "contracts": "Contracts",
    "reports": "Reports",
    "training": "Training Materials",
    "policies": "Company Policies",
    "invoices": "Invoices",
    "forms": "Forms & Templates",
    "personal_records": "Personal Records",
    // Analytics specific
    analyticsTitle: "AI Performance Analytics",
    requestsToday: "Requests Today",
    estRpd: "Est. RPD",
    avgLatency: "Avg Latency",
    errorRate: "Error Rate",
    date: "Date",
    model: "Model",
    reqs: "Reqs",
    tokens: "Tokens",
    time: "Time (ms)",
    err: "Errors",
    noData: "No data available for the selected period.",
    today: "Today",
    week: "This Week",
    month: "This Month",
    custom: "Custom Range",
    allModels: "All Models"
  },
  vi: {
    superadmin: "Super Admin (Root)",
    it: "Chuyên viên IT",
    hr: "Quản lý Nhân sự (HR)",
    employee: "Nhân viên",
    loginTitle: "Quản lý tài liệu nội bộ",
    loginDesc: "Chọn vai trò để truy cập",
    loginBtn: "Đăng nhập Hệ thống",
    welcomeAdmin: "Quản lý Nhân sự và Tài liệu", 
    hrDesc: "Quản lý tài liệu, biểu mẫu công ty.",
    userDesc: "Tra cứu thông tin & Chatbot hỗ trợ.",
    tabDocs: "Kho Tài liệu",
    tabUsers: "Quản lý Người dùng",
    tabSystem: "Cấu hình Hệ thống",
    tabDocsDesc: "Tải lên, sắp xếp thư mục và quản lý file",
    tabUsersDesc: "Tạo tài khoản, phân quyền và bảo mật",
    settings: "Cài đặt Hệ thống",
    maintenance: "Chế độ Bảo trì",
    stats: "Thống kê Hệ thống",
    view: "Xem tài liệu",
    uploadTitle: "Nhập liệu Tài liệu mới",
    uploadDesc: "Tự động điều hướng Cloudinary/Supabase/Blob",
    duplicateWarning: "Tài liệu này đã tồn tại! Bạn có muốn ghi đè không?",
    noPermission: "Bạn không có quyền thực hiện hành động này.",
    saveConfig: "Lưu Cấu hình",
    download: "Tải về",
    back: "Đăng xuất",
    searchDocs: "Tìm kiếm tài liệu...",
    filterAll: "Tất cả định dạng",
    files: "Kho Tài liệu",
    edit: "Xem / Sửa",
    editDocTitle: "Chi tiết tài liệu",
    docContent: "Nội dung",
    cancel: "Đóng",
    save: "Lưu thay đổi",
    clear: "Xóa đoạn hội thoại",
    systemHealth: "Trạng thái Hệ thống",
    vectorDb: "CSDL Vector",
    storageUsage: "Hybrid Cloud Storage",
    aiModelLabel: "Mô hình AI",
    records: "Bản ghi",
    quota: "Tổng dung lượng (Đa nền tảng)",
    configTitle: "Cấu hình Hệ thống",
    inferenceEngine: "Công cụ Suy luận AI",
    optimized: "Lưu trữ Hỗn hợp đã kích hoạt",
    maintenanceMode: "Chế độ Bảo trì",
    maintenanceDesc: "Tắt quyền truy cập user để cập nhật",
    publicUpload: "Quyền Tải lên Công khai",
    publicUploadDesc: "Cho khách tải file (Không khuyến nghị)",
    maxFileSize: "Kích thước file tối đa (MB)",
    dbManagement: "Quản lý Database & Backup",
    backupData: "Sao lưu Dữ liệu Hệ thống",
    integrityCheck: "Kiểm tra Tính toàn vẹn",
    lastBackup: "Bản sao lưu gần nhất",
    tokenReport: "Báo cáo Hiệu suất AI",
    tokensUsed: "Token đã dùng",
    requests: "Lượt yêu cầu",
    modelStatus: "Trạng thái Model",
    logs: "Nhật ký Hệ thống",
    cloudCapacity: "Dung lượng Cloud",
    dragDrop: "Kéo & Thả nhiều tệp (Lên tới 250MB)",
    dbEmpty: "Không có dữ liệu phù hợp.",
    aiAssistant: "Trợ lý AI",
    entries: "mục",
    pdfDoc: "Tài liệu PDF",
    wordDoc: "Tài liệu Word",
    excelSheet: "Bảng tính Excel",
    textFile: "Tệp văn bản",
    imageFile: "Hình ảnh / Scan",
    rootAccess: "Đã cấp quyền Root. Quản lý bảo trì.",
    createUser: "Tạo Người dùng mới",
    userList: "Danh sách Người dùng",
    username: "Username",
    password: "Mật khẩu",
    role: "Phân quyền",
    create: "Tạo tài khoản",
    newChat: "Đoạn chat mới",
    chatHistory: "Gần đây",
    noHistory: "Chưa có lịch sử",
    "contracts": "Hợp đồng",
    "reports": "Báo cáo",
    "training": "Tài liệu đào tạo",
    "policies": "Chính sách công ty",
    "invoices": "Hóa đơn",
    "forms": "Biểu mẫu",
    "personal_records": "Hồ sơ nhân sự",
    // Analytics specific
    analyticsTitle: "Phân tích Hiệu suất AI",
    requestsToday: "Yêu cầu Hôm nay",
    estRpd: "RPD Ước tính",
    avgLatency: "Độ trễ TB",
    errorRate: "Tỷ lệ Lỗi",
    date: "Ngày",
    model: "Mô hình",
    reqs: "Yêu cầu",
    tokens: "Tokens",
    time: "Thời gian (ms)",
    err: "Lỗi",
    noData: "Không có dữ liệu cho giai đoạn đã chọn.",
    today: "Hôm nay",
    week: "Tuần này",
    month: "Tháng này",
    custom: "Tùy chọn",
    allModels: "Tất cả Mô hình"
  },
  zh: {
    superadmin: "超级管理员 (Root)",
    it: "IT 专家",
    hr: "人力资源 (HR)",
    employee: "员工",
    loginTitle: "内部文档管理",
    loginDesc: "选择您的角色以访问系统",
    loginBtn: "登录系统",
    welcomeAdmin: "人力资源与文档管理",
    hrDesc: "管理公司文档与表格。",
    userDesc: "访问内部知识库与模板。",
    tabDocs: "文档库",
    tabUsers: "用户管理",
    tabSystem: "系统控制台",
    tabDocsDesc: "上传，组织文件夹和管理文件",
    tabUsersDesc: "创建用户，分配角色和安全性",
    settings: "系统设置",
    maintenance: "维护模式",
    stats: "系统统计",
    view: "视图",
    uploadTitle: "导入新数据",
    uploadDesc: "支持 PDF, Word, Excel, 图片, TXT",
    duplicateWarning: "文件已存在！是否覆盖？",
    noPermission: "您没有执行此操作的权限。",
    saveConfig: "保存配置",
    download: "下载",
    back: "退出",
    searchDocs: "搜索文档...",
    filterAll: "所有类型",
    files: "文件",
    edit: "编辑",
    editDocTitle: "编辑文档",
    docContent: "内容",
    cancel: "取消",
    save: "保存",
    clear: "清除聊天",
    systemHealth: "系统健康",
    vectorDb: "向量数据库",
    storageUsage: "混合云存储",
    aiModelLabel: "AI 模型",
    records: "记录",
    quota: "配额 (多云结合)",
    configTitle: "系统配置",
    inferenceEngine: "AI 推理引擎",
    optimized: "混合存储模式已激活",
    maintenanceMode: "维护模式",
    maintenanceDesc: "禁用用户访问以进行更新",
    publicUpload: "公开上传权限",
    publicUploadDesc: "允许访客上传文件（不推荐）",
    maxFileSize: "最大文件大小 (MB)",
    dbManagement: "数据库管理与备份",
    backupData: "备份系统数据",
    integrityCheck: "数据完整性检查",
    lastBackup: "最后备份时间",
    tokenReport: "AI 性能分析",
    tokensUsed: "已用代币",
    requests: "请求数",
    modelStatus: "模型状态",
    logs: "系统日志",
    cloudCapacity: "内部云容量",
    dragDrop: "拖放多个文件",
    dbEmpty: "数据库为空或无匹配.",
    aiAssistant: "AI 助手",
    entries: "条目",
    pdfDoc: "PDF 文档",
    wordDoc: "Word 文档",
    excelSheet: "Excel 表格",
    textFile: "文本文件",
    imageFile: "图片 / 扫描件",
    rootAccess: "Root 权限已授予. 系统维护模式管理.",
    createUser: "创建新用户",
    userList: "用户列表",
    username: "用户名",
    password: "密码",
    role: "角色",
    create: "创建",
    newChat: "新聊天",
    chatHistory: "历史记录",
    noHistory: "无近期记录",
    "contracts": "合同",
    "reports": "报告",
    "training": "培训资料",
    "policies": "公司政策",
    "invoices": "发票",
    "forms": "表格与模板",
    "personal_records": "人事档案",
    // Analytics specific
    analyticsTitle: "AI 性能分析仪表板",
    requestsToday: "今日请求",
    estRpd: "预计 RPD",
    avgLatency: "平均延迟",
    errorRate: "错误率",
    date: "日期",
    model: "模型",
    reqs: "请求",
    tokens: "代币",
    time: "时间 (ms)",
    err: "错误",
    noData: "所选期间无数据。",
    today: "今天",
    week: "本周",
    month: "本月",
    custom: "自定义范围",
    allModels: "所有模型"
  }
};

export const BACKEND_FILES: BackendFile[] = [
  {
    name: 'db/schema.ts',
    path: 'db/schema.ts',
    language: 'typescript',
    content: `import { pgTable, text, timestamp, integer, boolean } from 'drizzle-orm/pg-core';
export const documents = pgTable('documents', {
  id: text('id').primaryKey(),
  name: text('name').notNull(),
  content: text('content'),
  role_required: text('role_required').default('employee'),
  created_at: timestamp('created_at').defaultNow(),
});`
  }
];
